server.port=${PORT:8081}

# Give your application a cool hackathon name
spring.application.name=NiScamKe-Backend

# For local testing without crashing, tell Spring Boot to use a built-in memory bank
spring.datasource.url=jdbc:h2:mem:niscamkedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Show SQL queries in the terminal so we can see what's happening
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Gemini API key
gemini.api.key=${GEMINI_API_KEY:}
